version: "3.8"

services:
  api:
    build: ./xp-academy-api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/xp_academy
      - REDIS_URL=${REDIS_URL} # Pulls from your machine
      - JWT_SECRET=super_secret_docker_key
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
